name: GH-pages

on:
  # schedule:
  #  - cron: "* 16 * * *"
  push:
    branches:
      - source

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: yarn install
      - name: Prepare json
        run: yarn prepare-json
        env:
          VIGOTECH_MEMBERS_SOURCE: /vigotech.json
          VIGOTECH_MEMBERS_SOURCE_FILE: static/vigotech.json
          VIGOTECH_MEMBERS_SOURCE_GENERATED: /vigotech-generated.json
          VIGOTECH_MEMBERS_SOURCE_GENERATED_FILE: static/vigotech-generated.json
          VIGOTECH_FRIENDS_SOURCE: /friends.json
          MEETUP_API_BASE: 'http://api.meetup.com'
          EVENTBRITE_OAUTH_TOKEN: ${{ secrets.EVENTBRITE_OAUTH_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      - name: Build
        run: yarn generate:gh-pages
        env:
          GA: 'UA-98368785-1'
          VIGOTECH_FRIENDS_SOURCE: /friends.json
          VIGOTECH_MEMBERS_SOURCE_GENERATED: /vigotech-generated.json
          VIGOTECH_MEMBERS_SOURCE: /vigotech.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: master
